[workspace]
resolver = "3"
members = [
    "lib/component-map",
    "lib/concrete-type",
    "lib/idx-core",
    "lib/socket-reconnect",
]

[workspace.package]
edition = "2024"
authors = ["JustAStream <justastream.code@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/just-a-stream/open-core"

[workspace.lints.rust]
unsafe_code = "forbid"
unused = { level = "warn", priority = -1 }
missing_debug_implementations = "warn"
rust_2018_idioms = { level = "warn", priority = -1 }
unused_crate_dependencies = "warn"

[workspace.lints.clippy]
cognitive_complexity = "warn"
missing_const_for_fn = "warn"
redundant_pub_crate = "warn"
unused_self = "warn"
use_self = "warn"
type_complexity = "allow"
too_many_arguments = "allow"

[workspace.dependencies]
# Workspace crates
concrete-type = { path = "lib/concrete-type", version = "0.3" }

# Async
futures = { version = "0.3", default-features = false }
pin-project = { version = "1.1", default-features = false }
tokio = { version = "1.53", default-features = false }
tokio-stream = { version = "0.1", default-features = false }
tokio-test = { version = "0.4", default-features = false }

# Util
derive_more = { version = "2.1", default-features = false }
thiserror = { version = "2.0", default-features = false }

# Macros
convert_case = { version = "0.12", default-features = false }
proc-macro2 = { version = "1.0", default-features = false }
quote = { version = "1.0", default-features = false }
syn = { version = "3.0", default-features = false }

# Serialisation
serde = { version = "1.0", default-features = false }
